// Standalone test using OLD WORKING Facebook implementation from c4ad8ea commit
const FACEBOOK_PAGE_TOKEN = "EAAPCVgodoZCIBPca69MUJq6WNdbeUoZCAO8nKyiFVmpuJO5dwNA99JzzEASwNUQsi1a6qVWOo8FolOGNdk0qVZCl3wOeNpSrFbw0Yyvw2DLmPm3JGg1SNXrQD9nyemZA87ZCk1i9deyZAheoF4ZCFI22DZBVfruOCjfgju9rAqRnEBmyVED75B3qOoZAXTyUdDMMuCqrtXEpbbqrIRgefSstC06CJhyvn7E4UWLrAbNa0f1RnQw0CwAZDZD";
const FACEBOOK_RECIPIENT_ID = "10163155915743620";

async function sendOldFacebookTest() {
  console.log('🧪 Testing OLD WORKING Facebook implementation...');
  
  // Create test trading summary like the old working version
  const summaryText = `📊 Daily Trading Summary - ${new Date().toLocaleDateString()}

📈 Today's Analysis (5 symbols):

💭 AAPL: HOLD NEUTRAL
   💰 $238.47 | 68.2%
   NEUTRAL price prediction (TFT+N-HITS-Ensemble)...

💭 TSLA: HOLD NEUTRAL  
   💰 $334.09 | 67.8%
   NEUTRAL price prediction (TFT+N-HITS-Ensemble)...

💭 MSFT: HOLD NEUTRAL
   💰 $505.35 | 67.7% 
   NEUTRAL price prediction (TFT+N-HITS-Ensemble)...

💭 GOOGL: HOLD NEUTRAL
   💰 $230.66 | 69.4%
   NEUTRAL price prediction (TFT+N-HITS-Ensemble)...

💭 NVDA: HOLD NEUTRAL
   💰 $170.62 | 67.7%
   NEUTRAL price prediction (TFT+N-HITS-Ensemble)...

📊 Performance Metrics:
• Success Rate: 100.0%
• Average Confidence: 68.2%
• High Confidence Signals: 0
• Signal Distribution: {"BUY":0,"SELL":0,"HOLD":5}

🤖 Generated by TFT Trading System`;

  try {
    console.log('📤 Sending Facebook message using OLD WORKING implementation...');
    
    // EXACT OLD WORKING implementation from c4ad8ea commit
    const response = await fetch(`https://graph.facebook.com/v18.0/me/messages`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${FACEBOOK_PAGE_TOKEN}`
      },
      body: JSON.stringify({
        recipient: { id: FACEBOOK_RECIPIENT_ID },
        message: { text: summaryText },
        messaging_type: 'UPDATE'
      })
    });

    const result = await response.json();
    
    if (response.ok) {
      console.log('✅ SUCCESS! Old Facebook implementation worked:', JSON.stringify(result, null, 2));
    } else {
      console.log('❌ Old Facebook implementation failed:', JSON.stringify(result, null, 2));
    }

  } catch (error) {
    console.error('❌ Network error:', error.message);
  }
}

// Run the test
sendOldFacebookTest();