# Cloud-Native TFT Trading System - Wrangler Configuration
# Pure cloud architecture: Cloudflare Workers + ModelScope Cloud + Cloudflare AI

name = "tft-trading-cloud-native"
main = "cloudflare-worker-cloud-native.js"
compatibility_date = "2024-01-01"

# Cron triggers for pre-market analysis (6:30-9:00 AM EST)
[triggers]
crons = [
  "30 11 * * 1-5",  # 6:30 AM EST (11:30 UTC) Mon-Fri
  "0 12 * * 1-5",   # 7:00 AM EST (12:00 UTC) Mon-Fri  
  "0 13 * * 1-5",   # 8:00 AM EST (13:00 UTC) Mon-Fri
  "30 13 * * 1-5",  # 8:30 AM EST (13:30 UTC) Mon-Fri
  "0 14 * * 1-5"    # 9:00 AM EST (14:00 UTC) Mon-Fri
]

# KV namespace for storing analysis results
[[kv_namespaces]]
binding = "TRADING_RESULTS"
id = "321593c6717448dfb24ea2bd48cde1fa"
preview_id = "220ca67255ed4bfeada7eb6816ce6413"

# Cloudflare AI binding for sentiment analysis
[ai]
binding = "AI"

# Environment variables
[vars]
EMAIL_ENABLED = "false"
WORKER_VERSION = "2.0-cloud-native"
TIMEZONE = "America/New_York"
ARCHITECTURE = "cloudflare-workers-modelscope-cloud"

# Cloud service secrets (set via: wrangler secret put SECRET_NAME)
# Required secrets:
# - MODELSCOPE_API_KEY: API key for ModelScope cloud services
#
# Optional secrets:
# - SLACK_WEBHOOK_URL: Slack webhook for alerts
# - ALERT_EMAIL: Email address for trading alerts  
# - FACEBOOK_PAGE_TOKEN: Facebook Messenger bot token
# - FACEBOOK_RECIPIENT_ID: Your Facebook user ID
# - LINE_CHANNEL_TOKEN: LINE messaging API token
# - LINE_USER_ID: Your LINE user ID