#!/bin/bash

# Weekly Review Pipeline & Parameter Regression Test
# Verifies:
# - Full lifecycle: Trigger -> D1 Write -> Parameterized UI Read
# - Week anchor consistency between cron and UI
# - ?week=last returns correct previous week

set -euo pipefail

# Configuration
API_URL="${API_URL:-https://tft-trading-system.yanggf.workers.dev}"
API_KEY="${X_API_KEY:-}"

if [[ -z "$API_KEY" ]]; then
  echo "Error: X_API_KEY environment variable is not set"
  exit 1
fi

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log() { echo -e "${GREEN}[INFO]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

TESTS_PASSED=0
TESTS_FAILED=0

pass() { log "✓ $1"; TESTS_PASSED=$((TESTS_PASSED + 1)); }
fail_soft() { warn "✗ $1"; TESTS_FAILED=$((TESTS_FAILED + 1)); }

# 1. Trigger Weekly Job
log "Triggering manual weekly_review_analysis job..."
TRIGGER_RESPONSE=$(curl -s -X POST "$API_URL/api/v1/jobs/trigger" \
  -H "Content-Type: application/json" \
  -H "X-API-Key: $API_KEY" \
  -d '{"triggerMode": "weekly_review_analysis"}')

if echo "$TRIGGER_RESPONSE" | grep -q '"success":true'; then
  pass "Job triggered successfully"
else
  error "Failed to trigger job: $TRIGGER_RESPONSE"
fi

# 2. Verify Structured D1 Snapshot via API
log "Verifying latest weekly snapshot..."
# Wait a moment for D1 eventual consistency/processing if needed
sleep 2

LATEST_RESPONSE=$(curl -s "$API_URL/api/v1/jobs/latest?type=weekly" \
  -H "X-API-Key: $API_KEY")
EXECUTION_DATE=$(echo "$LATEST_RESPONSE" | jq -r '.data.executionDate // .executionDate // empty')

if [[ -z "$EXECUTION_DATE" || "$EXECUTION_DATE" == "null" ]]; then
  warn "Could not find latest weekly execution date from API"
  # Use today's date as fallback for testing
  EXECUTION_DATE=$(date +%Y-%m-%d)
else
  pass "Latest weekly execution date retrieved: $EXECUTION_DATE"
fi

# 3. Test Parameter: ?week=last
log "Testing parameter: ?week=last"
WEEK_LAST_HTML=$(curl -s -L "$API_URL/weekly-review?week=last")

if echo "$WEEK_LAST_HTML" | grep -q "Weekly Trading Review"; then
  pass "UI verified for ?week=last"
else
  error "UI check failed for ?week=last (HTML missing title)"
fi

# Verify Dual Model Stats in HTML
if echo "$WEEK_LAST_HTML" | grep -q "AI Model Performance" && echo "$WEEK_LAST_HTML" | grep -q "Gemma Sea Lion"; then
  pass "Dual model statistics found in HTML"
else
  warn "Dual model statistics section NOT found in HTML - check if job data includes modelStats"
fi

# 4. Test Parameter: Specific Date
log "Testing parameter: ?week=$EXECUTION_DATE"
SPECIFIC_DATE_HTML=$(curl -s -L "$API_URL/weekly-review?week=$EXECUTION_DATE")

if echo "$SPECIFIC_DATE_HTML" | grep -q "Weekly Trading Review"; then
  pass "UI verified for specific week date"
else
  fail_soft "UI check failed for ?week=$EXECUTION_DATE"
fi

# 5. D1 Alignment Check
log "Validating D1 data alignment..."
HAS_MODEL_STATS=$(echo "$LATEST_RESPONSE" | jq '.data.data.modelStats != null' 2>/dev/null || echo "false")

if [[ "$HAS_MODEL_STATS" == "true" ]]; then
  pass "D1 snapshot includes structured model performance data"
else
  warn "D1 snapshot missing modelStats - check weekly-review-analysis.ts logic"
fi

# 6. Validate Week Range Display (Sunday-Saturday range shown in HTML)
log "Validating week range display..."

# The HTML shows a Sunday-Saturday range in the date-display section
if echo "$WEEK_LAST_HTML" | grep -qE '[0-9]{1,2}/[0-9]{1,2}/[0-9]{4}.*-.*[0-9]{1,2}/[0-9]{1,2}/[0-9]{4}'; then
  pass "Week range format is valid (date - date)"
else
  warn "Could not validate week range format in HTML"
fi

# 7. Test ?week=last specifically targets previous week, not current
log "Verifying ?week=last targets the previous week..."

# Get current week data
CURRENT_WEEK_HTML=$(curl -s -L "$API_URL/weekly-review")

# Check that ?week=last shows "Week of" with a date (past week indicator)
if echo "$WEEK_LAST_HTML" | grep -q "Week of"; then
  pass "?week=last correctly shows 'Week of' (past week)"
elif echo "$WEEK_LAST_HTML" | grep -q "This Week"; then
  fail_soft "?week=last shows 'This Week' - may indicate incorrect week calculation"
else
  warn "Could not determine week label in ?week=last response"
fi

# 8. Verify cron-generated data matches UI lookup key
log "Verifying week anchor alignment between cron and UI..."

# Both scheduler.ts and UI's getWeekSunday() should use the same Sunday anchor
# After fixes: cron uses estTime (current Sunday), UI uses getWeekSunday() (current Sunday)
# So visiting /weekly-review on Sunday should show data generated by that Sunday's cron

# Check if current week has data (indicates alignment)
if echo "$CURRENT_WEEK_HTML" | grep -q "No Weekly Data Available\|No data available"; then
  warn "Current week shows no data - cron may not have run yet, or alignment issue"
else
  pass "Current week has data available"
fi

# 9. Summary
echo ""
log "=========================================="
log "Weekly Pipeline Regression Test Summary"
log "=========================================="
log "Tests Passed: $TESTS_PASSED"
log "Tests with Warnings: $TESTS_FAILED"

if [[ $TESTS_FAILED -gt 2 ]]; then
  error "Too many test failures ($TESTS_FAILED) - investigate issues"
fi

log "Regression tests completed!"
